name: Lint & Test & Build [Push]

on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-push-build
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install & build
        run: |
          npm ci
          npm run bootstrap:all
          npm run build:all
      - name: lint
        run: |
          npm run lint
      - name: test
        run: |
          npm run test:all:coverage
      - name: npm run test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        #if: github.ref == 'refs/heads/master'
        if: 1 == 0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/packages/**/coverage/lcov.info:lcov
